services:
  - type: web
    name: employeemanagement-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 10000
