services:
  - type: web
    name: employeemanagement
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 10000
      - key: SPRING_DATASOURCE_DRIVER
        value: com.mysql.cj.jdbc.Driver
